### ISSUE TITLE
Issues on Analysing Fish eDNA Data

### ISSUE THREAD

**Issue by Tricksie28** [billzt/MiFish#11]
Good day!

I have issues regarding analyzing my fish eDNA data on your website. It took hours to run it. It’s not yet analyzed. It’s almost 24 hrs but it is still running. Can you lend me a help on how can I troubleshoot my data? Thank you.
[Fish_eDNA_10_1.fastq.gz](https://github.com/billzt/MiFish/files/13958307/Fish_eDNA_10_1.fastq.gz)
[Fish_eDNA_10_2.fastq.gz](https://github.com/billzt/MiFish/files/13958311/Fish_eDNA_10_2.fastq.gz)
[Fish_eDNA_11_1.fastq.gz](https://github.com/billzt/MiFish/files/13958313/Fish_eDNA_11_1.fastq.gz)
[Fish_eDNA_11_2.fastq.gz](https://github.com/billzt/MiFish/files/13958315/Fish_eDNA_11_2.fastq.gz)

**Comment by tao-bioinfo** [comment]
Hi @Tricksie28 

Thank you for your issue.

The main reason is that your sequences are not from fish, but from bacteria. The analysis process has already stopped due to too few valid sequences.

I test the first ten reads of `Fish_eDNA_10_1.fastq.gz`

[test.first10reads.fa.txt](https://github.com/billzt/MiFish/files/13962001/test.first10reads.fa.txt)

Using https://blast.ncbi.nlm.nih.gov/Blast.cgi to search them against nt_prok + nt_euk, I found that they are all from bacteria, fungi, or other micro-organisms.

For example, the first read seems originated from bacteria
```
>M05881:549:000000000-LB3K3:1:1102:15045:1171 1:N:0:GCCATATAAC+ACACAATATC
GTCGGTAAAACTCGTGCCAGCAGCCGCGGTAATACGGAGGGTCCGAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTTTGTCAGTCAGATGTGAAAGCCCAGGGCTCAACCTTGGAACTGCACCTGATACTGCAAGACTAGAGTACAATAGAGGGGAGTGGAATTTCCGGTGTAGCGGTGAAATGCGTAGAGATCGGAAGGAACACCAGTGGCGAAGGCGACTCCCTGGATTGATACTGTCACTGAGGTGCGAAAGCGTGGGGAGGAAACTGGGATTAGATACCCCACT
```

![image](https://github.com/billzt/MiFish/assets/1146090/25dd342e-adc7-4547-a44e-56813dec496f)
![image](https://github.com/billzt/MiFish/assets/1146090/610ce006-4e45-4821-9487-15fd808bb25d)
