### ISSUE TITLE
Example files of multi-fast format: MiFish Pipeline web version

### ISSUE THREAD

**Issue by jimsingleton** [billzt/MiFish#4]
Hi,

Could you send me example files of multi-fasta format for MiFish Pipeline web version?
http://mitofish.aori.u-tokyo.ac.jp/mifish/
I am interested in species/group name assignments of eDNA sequences (FASTA format).
In this web version, I can find two example files of .fastq.gz format, 
but I cannot find example files of fasta format.

Thank you

**Comment by tao-bioinfo** [comment]
[s3.fa.xz.zip](https://github.com/billzt/MiFish/files/11182756/s3.fa.xz.zip)

@jimsingleton Hi, please try this file. (Because GitHub has limitations on the formats of uploading files,  please unzip it to obtain `s3.fa.xz` and then run with it.)

FASTA format can be the merged results of pair-end reads, or raw sequences of single-end reads.

**Comment by jimsingleton** [comment]
Dear billzt,

Thank you. Your file (se.fa.xz) worked for MiFish Pipeline web version.
